name: Image Push

on:
  workflow_call:
    inputs:
      context:
        required: true
        type: string
      tags:
        required: true
        type: string

jobs:
  dockerhub-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.context }}
          tags: ${{ inputs.tags }}
          push: true
