name: Image tag change

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      path:
        required: true
        type: string
      filename:
        required: true
        type: string
    secrets:
      dockerhub_username:
        required: true
      github_pat:
        required: true

jobs:
  tag-change:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          repository: DavoA/kubernetes-manifests
          token: ${{ secrets.github_pat }}

      - name: Configure Git
        run: |
          git config --global user.email "aristakesyandav@yandex.ru"
          git config --global user.name "DavoA"
          
      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.31.2/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq 
          
      - name: Update YAML file with yq
        working-directory: kubernetes-manifests
        run: |
          yq '.spec.template.spec.containers.[0].image = "${{ secrets.dockerhub_username }}/${{inputs.image}}:${{ github.sha }}"' -i ${{inputs.path}}/${{inputs.filename}}

      - name: Push to destination repository
        run: |
          git remote add destination https://x-access-token:${{ secrets.github_pat }}@github.com/DavoA/kubernetes-manifests.git
          git push destination main


          
